sudo: false
language: java
services:
- docker
cache:
  directories:
  - "$HOME/.cache"
env:
  global:
  - secure: k3RPLLaMCVfAe/uDPT/faXDHy5yns38OhY8GGRYlRt/ukbKdKLJQ3CkRJ2ckgykUMAQBtlrPRRat7gY8OR3FkQB2TBXafeWTouIRDmL12EFAWVyK1c3O5l5mTJN7CKiZWy0wYQv8tCCl3NMDxJU5sHt/x/HRa4h1Rvx2nGjrYiP6rhJqOv68FqfvXzIhdx6tmxzVB6eJ1bR6zGKxkjnIHVugs0RrtcHTQPfa7+J7mF4b3L3uKjcRIMRpXREOaSNt/Uxlbb93KjkzPxrdWyLbd4Rc/dVZjIiOLcMNmqAq2joYBCYuEWT57Q7VknRc4f40pLe3324xKza9wqWGo8LOrALxBpAEYnTfWdS+XgOXY8PV/z3frAlRfsEAEjsgoE3N5nldVFfmD3E+R62tzdRfGvjQdhVxs37YvPKffDxvfbfVVnaTG4/VLZPAb9eVg5As44Ey76qbqlfZ6GC6/OF/jado7z2xz5wSbqRVIIT/ny61ef5Gc7dGfgYFSn0MBdmAHvyMaVWYVMFrlRrKWgcTe0SunAEgKHfhomTY4qOz+R7UWW0QUfNvL2xjE9ZWvZ+AYS/jWG2ywr6LkJHe4b5IanuWl0Jpl2er0qqxE46Mu/1+jnK7bugHwBXXqFwn7kFhwU5a0fJ7GJj4NEn9ycRq8AdfoD5wWRq36cDQ++1cF68=
  - secure: R4NLLMMNrbH3CvweBoMePlTEJvG8nDltBJrLAmLQwEFIQK8mpjdGY5nbsMcvnMnABgc8pPsQLqTcxI8RcFxR051zu+fUFM3J5aP6tzLgnebcncepgUVYn57FlmkHe/TdS/1XBqDJVnWUbhVyN8XmEn4wjkpM6PRd5HkBspo73mWGH5JKB3b1P3mNs5BOJ0t7r+TBntWVNYdzZPpXER4Mul6tAIoYYKjh4i50eqKYKjQ7HAR/i649atUJ6N5KE1HAKC6NHqZ8TCV9mEdNE6/w0fPAQNveUYC3yn2NsHp0X42xTOmnrvn3aFp4PTL2ce1ZsxPuCkHgS7DafF9/8ikEQf3omofz5Gjp0DLpuyQqLbY/HUrc4pCM6oqLnG/74h9ziS43ty5jk7zaVuSnstRCl5Fk0r9KnV/+lB/J9AOaxxALN1rzagFVu7leU1dWS2TJmezVBHygrqFnCQsntDs/MAdvRZXVzmN2IVVWQFuxl+TXER7pYnYPffUtAas2nEhTiFqnpVwBlpCCPFoyEZBefHeIsgAo48Fy8DRlFbfGJCffdX/58tSRyVF2mHfQFy+WB42KfITnnVNGivcbPzNU158izuyrlS4P2wZzeRUGUH0aFB0Aq+1aw93qC3k3CcAoPUsoIsBTCYtHKiKNRiMDPRnL/l+cJVUTSc0yrvjvsw0=
  - secure: I++huIUKvbZt88FvMugYWxjQwqIbchkpABcT8zF1B7xIlsReCDv3VBjVXtEpy4MXjr5X1xSrTUjEbj7DcXm0z08lm7YJN7hXP3LBxz/e4TyHSZI9JeFdz+JQXyVAgHZlvJlA1wzlnL+JgdSZDFOfd5iseeWPFZLbsl+LWuff7peI5v2gqnj4jIrGKj9yQZvOTOE5J93MBDSNEJgcwAsm7S85h6gl9ooMVzwwPMkMT8LjET5CdV42eYbnhJ4Vh1VT+sFjVp7n7fiYNZbS90+EPuaB7bUm9dwQwPSeZ0t1Q/ODCKdcBqlVmVJ7/SW0NPie8Qupa/DHTjJ3/3YtI6fE4MPxx9vdFnyRlF+WsKvVVNxRpD9ZAT/Ihf48W493FGkCP+74z+kKRyUqclwyzO9IVAc85VhyfJ3Lv6jgTW28+CXSXCCk2DINO54Tch1BOwsV6Y5hkdF6ETXaGbtcTxZqPzX5Te8d0IzblMc/c8LZtSnah2u34WB9WdCLKQSE2supp1iCPy88MBOR7xbDP9ar3cT/EK0O2CN8vnyEKouHTVxe0+o7OHDL46IRupNQAs+nMQCdjbPvHcuP0yhinN80Stnhv3MFc5Ap1luF1z8x+zTWlzhaWjMLh++4OnTk9kyg3ZZhbWN5awaZ6+v5S2RcK1DoY4WgwGQ+LodvV4UMICI=
  - secure: K6fdAUNz3fYuTLIcGf8VlWvXf9EOBh7EmMFhZybVwiEY3cUXg4xOOZjfnj3bFv+25hw5OFJj24E/NHNOxxM/fwtX1OhwgiQP2sQcQlpJc1lMbqOPl0hVKTmJIonBoxfXQ+4KsJF0UlFYLL+Y++sz+xdl7l1VSyun5v/pkHoTHsehA2I1CgiFYTk1Fq1Z2HM+tywdjtBsJeJliBHLmU/Rd4FZzux0vcn1Ee6TlDmw/MV6D1vePKPQREDFVK8Se9I8heNxMBiz0JBZi04bI4D4wcLGYOQ9Dwiv1UDSphbEcSC18Opi1HbMQ8QPO+DjjykqeB3fQNMoKaLDvU3VCreByfcPy++AAtCekOsV5CRI4cbQVFOuyrAxfDQnvpoN762Fuuw4L+0HKCqd/1Qgr/i0Wyg5lFwSva7jFsSaLq7Ienmk79yZNuUatt3NvICUcZviJtp1KvpqxfE8nhj+svQ3kxE7hLMVYX7A2KQGIKVN8p5ad0IsKC1HoEoYktHxBTyqCz5qdf5iEnRKSc7/d5m+IubjbNokH1zl73G6upu8zHnrKBOfWbRK0F3AErkjHmPOxnc3dcUn2+EAQx2/fEIpFe7cSiP3qgQrRyWPJ5hxb6B+OuZLFseINORJdveVdjxE+PS2GfINBuExYFM//VQ+AitdQwZJrjdcCI5J0qPP5y8=
addons:
  sonarcloud:
    organization: cogpunk
    token:
      secure: Su+f+ClHWc7h/ONUWRdYvZ8IzSQJFHkQk16UTQoGrTH1Mzm8MDbNyL1udBQGMQMSOE/NxJkS2cpOdfa6nYuRymWR8cTz9YOYPo5ZrAAXKXXMt+0n43hHqawFwTM1Rt2KSB3ZLbpgAu7AM/FMcRNdgHwqyNPMspSXF1QToz2J507cqORNwCoQhypnqOAee0dy6JBo2c1X5EDKi5l27e15KLlJka0pAimMPuwMFy/Se4DzgL2E+d8y+XBigkXiOSzEQdY8E+DvQAZCCaNF0oUwucUxaVjZaOngvH9W477AQAFCuaE4OJMrIzb3prW7IqLq8yemFzV8BMCC5okWCCql++8O4r7CIIuwEAPJ4xkMtD+/kiWLM9qccajM5W388yPIz5uoZlDcKp7iVDdgHMMr+CE4OUhdjP5GbWQMC1erbNxo8u/Pb8myfHZ1PDEJemliGuw5b81ThVU2Vv0Ch+8Z+CYCsrzdxUKZcOOAjyngcU3ti1cqdu5pGM/OyZIp5PPeWpGPnoFWInpQcTg6z3LPueQe/LE60Mtvc/JUdaWb/yKhr356h3IhdtM8z7NpMZ1YezN+1fISq8mXBWqv92IUe3mVINxr4hbqM1UudmMRS1M7yCBTitBye4h/FmF3vpH1fOk3FaJ0f3ndLkZ5lMs/2amFDvbyQctfoTy5Po82iaw=
install: skip
script: "./scripts/test"
before_deploy:
- openssl aes-256-cbc -K $encrypted_4f0d00631887_key -iv $encrypted_4f0d00631887_iv
  -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
- gpg --fast-import --batch .travis/gpg.asc
deploy:
-
  provider: script
  script: "./scripts/deploy"
  skip_cleanup: true
  on:
    branch: main
-
  provider: script
  script: "./scripts/deploy"
  skip_cleanup: true
  on:
    tag: true
